#!/usr/bin/env python3
"""Generate fixed C wrappers and metadata from the pinned native declarations."""
import json
from pathlib import Path
import re

source=Path('vendor/opentui/packages/core/src/zig.ts').read_text()
table=source[source.index('const rawSymbols = dlopen('):source.index('if (env.OTUI_DEBUG_FFI')]
entries=[dict(name=m[1],args=['ptr' if t=='buffer' else t for t in re.findall(r'"(\w+)"',m[2])],returns=m[3])
         for m in re.finditer(r'(\w+):\s*\{\s*(?://[^\n]*\n\s*)*args:\s*\[([^\]]*)\],\s*returns:\s*"(\w+)"',table)]
assert len(entries)==423, f'Upstream FFI inventory changed: {len(entries)}'
allow=json.loads(Path('js/platform/symbols.json').read_text())
selected=[e for e in entries if e['name'] in allow]
assert len(selected)==len(allow), 'Unknown or duplicated native symbol'
sources=[(p,p.read_text()) for p in sorted(Path('vendor/opentui/packages/native/src').glob('*.zig'))]
def split_arguments(text):
    parts=[];start=depth=0
    for i,c in enumerate(text):
        if c=='(':depth+=1
        elif c==')':depth-=1
        elif c==',' and depth==0:parts.append(text[start:i]);start=i+1
    return [p.strip() for p in parts+[text[start:]] if p.strip()]
def native_type(t):
    t=t.strip()
    if '*' in t or t.endswith(('YGNodeRef','YGNodeConstRef')) or t=='?event_bus.EventCallback':return 'ptr'
    if t=='NativeHandle':return 'u32'
    if t in ['void','bool','u8','u16','u32','i32','f32','u64','usize']:return t
    raise ValueError(f'Unreviewed Zig ABI type: {t}')
def compatible(native,ffi):return native==ffi or (native=='bool' and ffi=='u8')
definitions={}
for e in selected:
    pattern=re.compile(r'(?:pub )?export fn '+re.escape(e['name'])+r'\(([\s\S]*?)\)\s*([^\{]+)\{')
    matches=[(path,text,pattern.search(text)) for path,text in sources if pattern.search(text)]
    assert len(matches)==1, f'Missing or ambiguous export {e["name"]}'
    path,text,match=matches[0];declaration=match[0]
    opening=declaration.index('(');closing=opening;depth=0
    while True:
        if declaration[closing]=='(':depth+=1
        elif declaration[closing]==')':depth-=1
        closing+=1
        if depth==0:break
    args=[native_type(arg.split(':',1)[1]) for arg in split_arguments(declaration[opening+1:closing-1])]
    returns=native_type(declaration[closing:-1])
    assert len(args)==len(e['args']) and all(compatible(n,f) for n,f in zip(args,e['args'])) and compatible(returns,e['returns']),f'Signature differs: {e["name"]}'
    definitions[e['name']]=dict(args=args,returns=returns,source=f'{path}:{text[:match.start()].count(chr(10))+1}')
types=dict(ptr='void *',void='void',bool='bool',u8='uint8_t',u16='uint16_t',u32='uint32_t',i32='int32_t',u64='uint64_t',i64='int64_t',f32='float',f64='double',usize='size_t')
code=['/* Generated by scripts/generate-bindings.py. */','#include "native_bridge.h"']
for e in selected:
    name=e['name'];native=definitions[name]
    assert all(t in types for t in e['args']+[e['returns']]),f'Unknown ABI type in {name}'
    arguments=', '.join(f'{types[t]} a{i}' for i,t in enumerate(native['args'])) or 'void'
    code += [f'extern {types[native["returns"]]} {name}({arguments});',
             f'static JSValue wrap_{name}(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {{',
             f'(void)self; if (argc != {len(e["args"])}) return JS_ThrowTypeError(ctx, "{name}: wrong argument count");']
    for i,t in enumerate(e['args']):
        if t=='ptr':line=f'void *a{i}; if (qt_pointer(ctx, argv[{i}], &a{i}) < 0) return JS_EXCEPTION;'
        elif t=='bool':line=f'int a{i} = JS_ToBool(ctx, argv[{i}]); if (a{i} < 0) return JS_EXCEPTION;'
        elif t in ('f32','f64'):line=f'double a{i}; if (JS_ToFloat64(ctx, &a{i}, argv[{i}]) < 0) return JS_EXCEPTION;'
        elif t in ('u64','i64','usize'):line=f'int64_t a{i}; if (JS_ToBigInt64(ctx, &a{i}, argv[{i}]) < 0) return JS_EXCEPTION;'
        else:line=f'{"int32_t" if t=="i32" else "uint32_t"} a{i}; if ({"JS_ToInt32" if t=="i32" else "JS_ToUint32"}(ctx, &a{i}, argv[{i}]) < 0) return JS_EXCEPTION;'
        code.append(line)
    if name=='setUseThread':code.append('if(a1) return JS_ThrowTypeError(ctx, "The counter profile requires same-thread native rendering");')
    if name=='createRenderer':code.append('if(a4) return JS_ThrowTypeError(ctx, "Custom native output feeds are unsupported");')
    views=['bufferGetCharPtr','bufferGetFgPtr','bufferGetBgPtr','bufferGetAttributesPtr']
    if name in views:code += [f'return qt_buffer_view(ctx,a0,{views.index(name)});','}'];continue
    if name in ('destroyOptimizedBuffer','bufferResize'):code.append('qt_views_invalidate(a0);')
    if name in ('resizeRenderer','destroyRenderer'):code.append('qt_views_clear();')
    call=f'{name}('+', '.join(f'({types[t]})a{i}' for i,t in enumerate(e['args']))+')'
    t=e['returns']
    if t=='void':code.append(f'{call}; return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;')
    else:
        if t=='ptr':ret='JS_NewBigUint64(ctx, (uintptr_t)value)'
        elif t=='bool':ret='JS_NewBool(ctx, value)'
        elif t.startswith('f'):ret='JS_NewFloat64(ctx, value)'
        elif t in ('u64','usize'):ret='JS_NewBigUint64(ctx, value)'
        elif t=='i64':ret='JS_NewBigInt64(ctx, value)'
        elif t=='i32':ret='JS_NewInt32(ctx, value)'
        else:ret='JS_NewUint32(ctx, value)'
        code.append(f'{types[t]} value = {call}; if (qt_callback_failed(ctx)) return JS_EXCEPTION; return {ret};')
    code.append('}')
code += ['int qt_register_symbols(JSContext *ctx, JSValue global) {','JSValue symbols = JS_NewObject(ctx);']
for e in selected:
    name=e['name'];code.append(f'if (JS_SetPropertyStr(ctx, symbols, "{name}", JS_NewCFunction(ctx, wrap_{name}, "{name}", {len(e["args"])})) < 0) {{ JS_FreeValue(ctx, symbols); return -1; }}')
code += ['return JS_SetPropertyStr(ctx, global, "__native", symbols);','}']
Path('src/native_generated.c').write_text('\n'.join(code)+'\n')
Path('js/platform/bindings.json').write_text(json.dumps([dict(e,native=definitions[e['name']]) for e in selected],indent=2)+'\n')
