// Generate fixed C wrappers from the pinned OpenTUI FFI declarations.
// A checked-in allowlist limits the runtime registry to the counter profile.
const source = await Bun.file("vendor/opentui/packages/core/src/zig.ts").text();
const table = source.slice(source.indexOf("const rawSymbols = dlopen("), source.indexOf("if (env.OTUI_DEBUG_FFI"));
const entries = [...table.matchAll(/(\w+):\s*\{\s*(?:\/\/[^\n]*\n\s*)*args:\s*\[([^\]]*)\],\s*returns:\s*"(\w+)"/g)].map((m) => ({
  name: m[1], args: [...m[2].matchAll(/"(\w+)"/g)].map(x => x[1] === "buffer" ? "ptr" : x[1]), returns: m[3],
}));
if (entries.length !== 423) throw new Error(`Upstream FFI inventory changed: ${entries.length}`);
const allow = await Bun.file("js/platform/symbols.json").json();
const selected = entries.filter(e => allow.includes(e.name));
if (selected.length !== allow.length) throw new Error("Unknown or duplicated native symbol");
const nativeSources=await Promise.all([...new Bun.Glob("*.zig").scanSync("vendor/opentui/packages/native/src")].map(async name=>({
  path:`vendor/opentui/packages/native/src/${name}`,text:await Bun.file(`vendor/opentui/packages/native/src/${name}`).text(),
})));
function splitArguments(text:string){
  const parts:string[]=[];let start=0,depth=0;
  for(let i=0;i<text.length;i++){
    if(text[i]==="(")depth++;else if(text[i]===")")depth--;
    else if(text[i]===","&&depth===0){parts.push(text.slice(start,i));start=i+1}
  }
  parts.push(text.slice(start));return parts.map(x=>x.trim()).filter(Boolean);
}
function nativeType(type:string){
  type=type.trim();
  if(type.includes("*")||type.endsWith("YGNodeRef")||type.endsWith("YGNodeConstRef")||type==="?event_bus.EventCallback")return "ptr";
  if(type==="NativeHandle")return "u32";
  if(["void","bool","u8","u16","u32","i32","f32","u64","usize"].includes(type))return type;
  throw new Error(`Unreviewed Zig ABI type: ${type}`);
}
const nativeDefinitions=new Map<string,{args:string[],returns:string,source:string}>();
for(const entry of selected){
  const pattern=new RegExp(`(?:pub )?export fn ${entry.name}\\(([\\s\\S]*?)\\)\\s*([^\\{]+)\\{`);
  const file=nativeSources.find(file=>pattern.test(file.text));
  if(!file)throw new Error(`Missing native export ${entry.name}`);
  const match=file.text.match(pattern)!;
  const declaration=match[0];
  const open=declaration.indexOf("(");let close=open,depth=0;
  do{if(declaration[close]==="(")depth++;else if(declaration[close]===")")depth--;close++}while(depth>0&&close<declaration.length);
  const args=splitArguments(declaration.slice(open+1,close-1)).map(arg=>nativeType(arg.slice(arg.indexOf(":")+1)));
  const returns=nativeType(declaration.slice(close,-1));
  const compatible=(native:string,ffi:string)=>native===ffi || (native==="bool"&&ffi==="u8");
  if(args.length!==entry.args.length||!args.every((type,i)=>compatible(type,entry.args[i]))||!compatible(returns,entry.returns))throw new Error(`Native signature differs from FFI declaration: ${entry.name}`);
  nativeDefinitions.set(entry.name,{args,returns,source:`${file.path}:${file.text.slice(0,match.index).split("\n").length}`});
}
const types: Record<string, string> = {ptr:"void *",void:"void",bool:"bool",u8:"uint8_t",u16:"uint16_t",u32:"uint32_t",i32:"int32_t",u64:"uint64_t",i64:"int64_t",f32:"float",f64:"double",usize:"size_t"};
const code = ['/* Generated by scripts/generate-bindings.ts. */', '#include "native_bridge.h"'];
for (const e of selected) {
  if (![...e.args,e.returns].every(t=>types[t])) throw new Error(`Unknown ABI type in ${e.name}`);
  const native=nativeDefinitions.get(e.name)!;
  code.push(`extern ${types[native.returns]} ${e.name}(${native.args.map((t,i)=>`${types[t]} a${i}`).join(", ") || "void"});`);
  code.push(`static JSValue wrap_${e.name}(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {`, `(void)self; if (argc != ${e.args.length}) return JS_ThrowTypeError(ctx, "${e.name}: wrong argument count");`);
  e.args.forEach((t,i)=>{
    if(t === "ptr") code.push(`void *a${i}; if (qt_pointer(ctx, argv[${i}], &a${i}) < 0) return JS_EXCEPTION;`);
    else if(t === "bool") code.push(`int a${i} = JS_ToBool(ctx, argv[${i}]); if (a${i} < 0) return JS_EXCEPTION;`);
    else if(t === "f32" || t === "f64") code.push(`double a${i}; if (JS_ToFloat64(ctx, &a${i}, argv[${i}]) < 0) return JS_EXCEPTION;`);
    else if(t === "u64" || t === "i64" || t === "usize") code.push(`int64_t a${i}; if (JS_ToBigInt64(ctx, &a${i}, argv[${i}]) < 0) return JS_EXCEPTION;`);
    else code.push(`${t === "i32" ? "int32_t" : "uint32_t"} a${i}; if (${t === "i32" ? "JS_ToInt32" : "JS_ToUint32"}(ctx, &a${i}, argv[${i}]) < 0) return JS_EXCEPTION;`);
  });
  if(e.name==="setUseThread")code.push('if(a1) return JS_ThrowTypeError(ctx, "The counter profile requires same-thread native rendering");');
  if(e.name==="createRenderer")code.push('if(a4) return JS_ThrowTypeError(ctx, "Custom native output feeds are unsupported");');
  const viewKind=["bufferGetCharPtr","bufferGetFgPtr","bufferGetBgPtr","bufferGetAttributesPtr"].indexOf(e.name);
  if(viewKind>=0){code.push(`return qt_buffer_view(ctx,a0,${viewKind});`,"}");continue;}
  if(e.name==="destroyOptimizedBuffer"||e.name==="bufferResize")code.push("qt_views_invalidate(a0);");
  if(e.name==="resizeRenderer"||e.name==="destroyRenderer")code.push("qt_views_clear();");
  const call = `${e.name}(${e.args.map((t,i)=>`(${types[t]})a${i}`).join(", ")})`;
  if(e.returns === "void") code.push(`${call}; return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;`);
  else {
    const t=e.returns;
    const ret=t === "ptr" ? "JS_NewBigUint64(ctx, (uintptr_t)value)" : t === "bool" ? "JS_NewBool(ctx, value)" : t.startsWith("f") ? "JS_NewFloat64(ctx, value)" : t === "u64" || t === "usize" ? "JS_NewBigUint64(ctx, value)" : t === "i64" ? "JS_NewBigInt64(ctx, value)" : t === "i32" ? "JS_NewInt32(ctx, value)" : "JS_NewUint32(ctx, value)";
    code.push(`${types[t]} value = ${call}; if (qt_callback_failed(ctx)) return JS_EXCEPTION; return ${ret};`);
  }
  code.push("}");
}
code.push("int qt_register_symbols(JSContext *ctx, JSValue global) {", "JSValue symbols = JS_NewObject(ctx);");
for(const e of selected) code.push(`if (JS_SetPropertyStr(ctx, symbols, "${e.name}", JS_NewCFunction(ctx, wrap_${e.name}, "${e.name}", ${e.args.length})) < 0) { JS_FreeValue(ctx, symbols); return -1; }`);
code.push('return JS_SetPropertyStr(ctx, global, "__native", symbols);',"}");
await Bun.write("src/native_generated.c",code.join("\n")+"\n");
await Bun.write("js/platform/bindings.json",JSON.stringify(selected.map(entry=>({...entry,native:nativeDefinitions.get(entry.name)})),null,2)+"\n");
