/* Generated by scripts/generate-bindings.ts. */
#include "native_bridge.h"
extern void setLogCallback(void * a0);
static JSValue wrap_setLogCallback(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "setLogCallback: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
setLogCallback((void *)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t createEventSink(void * a0);
static JSValue wrap_createEventSink(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "createEventSink: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t value = createEventSink((void *)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void destroyEventSink(uint32_t a0);
static JSValue wrap_destroyEventSink(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "destroyEventSink: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
destroyEventSink((uint32_t)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t createNativeRenderable(void);
static JSValue wrap_createNativeRenderable(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 0) return JS_ThrowTypeError(ctx, "createNativeRenderable: wrong argument count");
uint32_t value = createNativeRenderable(); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void destroyNativeRenderable(uint32_t a0);
static JSValue wrap_destroyNativeRenderable(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "destroyNativeRenderable: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
destroyNativeRenderable((uint32_t)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern bool nativeRenderableAttachYogaNode(uint32_t a0, void * a1);
static JSValue wrap_nativeRenderableAttachYogaNode(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "nativeRenderableAttachYogaNode: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
bool value = nativeRenderableAttachYogaNode((uint32_t)a0, (void *)a1); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBool(ctx, value);
}
extern bool nativeRenderableSetMeasureTarget(uint32_t a0, uint32_t a1, uint32_t a2);
static JSValue wrap_nativeRenderableSetMeasureTarget(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "nativeRenderableSetMeasureTarget: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
bool value = nativeRenderableSetMeasureTarget((uint32_t)a0, (uint32_t)a1, (uint32_t)a2); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBool(ctx, value);
}
extern uint32_t createRenderer(uint32_t a0, uint32_t a1, uint8_t a2, uint8_t a3, void * a4);
static JSValue wrap_createRenderer(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 5) return JS_ThrowTypeError(ctx, "createRenderer: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
uint32_t a3; if (JS_ToUint32(ctx, &a3, argv[3]) < 0) return JS_EXCEPTION;
void *a4; if (qt_pointer(ctx, argv[4], &a4) < 0) return JS_EXCEPTION;
if(a4) return JS_ThrowTypeError(ctx, "Custom native output feeds are unsupported");
uint32_t value = createRenderer((uint32_t)a0, (uint32_t)a1, (uint8_t)a2, (uint8_t)a3, (void *)a4); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern bool setTerminalEnvVar(uint32_t a0, void * a1, uint32_t a2, void * a3, uint32_t a4);
static JSValue wrap_setTerminalEnvVar(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 5) return JS_ThrowTypeError(ctx, "setTerminalEnvVar: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
void *a3; if (qt_pointer(ctx, argv[3], &a3) < 0) return JS_EXCEPTION;
uint32_t a4; if (JS_ToUint32(ctx, &a4, argv[4]) < 0) return JS_EXCEPTION;
bool value = setTerminalEnvVar((uint32_t)a0, (void *)a1, (uint32_t)a2, (void *)a3, (uint32_t)a4); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBool(ctx, value);
}
extern void destroyRenderer(uint32_t a0, bool a1);
static JSValue wrap_destroyRenderer(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "destroyRenderer: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
int a1 = JS_ToBool(ctx, argv[1]); if (a1 < 0) return JS_EXCEPTION;
destroyRenderer((uint32_t)a0, (bool)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void setUseThread(uint32_t a0, bool a1);
static JSValue wrap_setUseThread(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "setUseThread: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
int a1 = JS_ToBool(ctx, argv[1]); if (a1 < 0) return JS_EXCEPTION;
if(a1) return JS_ThrowTypeError(ctx, "The counter profile requires same-thread native rendering");
setUseThread((uint32_t)a0, (bool)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void setBackgroundColor(uint32_t a0, void * a1);
static JSValue wrap_setBackgroundColor(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "setBackgroundColor: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
setBackgroundColor((uint32_t)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint8_t render(uint32_t a0, bool a1);
static JSValue wrap_render(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "render: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
int a1 = JS_ToBool(ctx, argv[1]); if (a1 < 0) return JS_EXCEPTION;
uint8_t value = render((uint32_t)a0, (bool)a1); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t getNextBuffer(uint32_t a0);
static JSValue wrap_getNextBuffer(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "getNextBuffer: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = getNextBuffer((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t getCurrentBuffer(uint32_t a0);
static JSValue wrap_getCurrentBuffer(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "getCurrentBuffer: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = getCurrentBuffer((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t getBufferWidth(uint32_t a0);
static JSValue wrap_getBufferWidth(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "getBufferWidth: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = getBufferWidth((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t getBufferHeight(uint32_t a0);
static JSValue wrap_getBufferHeight(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "getBufferHeight: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = getBufferHeight((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint8_t getBufferWidthMethod(uint32_t a0);
static JSValue wrap_getBufferWidthMethod(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "getBufferWidthMethod: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint8_t value = getBufferWidthMethod((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void bufferClear(uint32_t a0, void * a1);
static JSValue wrap_bufferClear(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "bufferClear: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
bufferClear((uint32_t)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t bufferGetRealCharSize(uint32_t a0);
static JSValue wrap_bufferGetRealCharSize(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "bufferGetRealCharSize: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = bufferGetRealCharSize((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t bufferWriteResolvedChars(uint32_t a0, void * a1, uint32_t a2, bool a3);
static JSValue wrap_bufferWriteResolvedChars(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 4) return JS_ThrowTypeError(ctx, "bufferWriteResolvedChars: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
int a3 = JS_ToBool(ctx, argv[3]); if (a3 < 0) return JS_EXCEPTION;
uint32_t value = bufferWriteResolvedChars((uint32_t)a0, (void *)a1, (uint32_t)a2, (bool)a3); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void resizeRenderer(uint32_t a0, uint32_t a1, uint32_t a2);
static JSValue wrap_resizeRenderer(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "resizeRenderer: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
resizeRenderer((uint32_t)a0, (uint32_t)a1, (uint32_t)a2); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint8_t bufferDrawImage(uint32_t a0, uint32_t a1, void * a2);
static JSValue wrap_bufferDrawImage(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "bufferDrawImage: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
void *a2; if (qt_pointer(ctx, argv[2], &a2) < 0) return JS_EXCEPTION;
uint8_t value = bufferDrawImage((uint32_t)a0, (uint32_t)a1, (void *)a2); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void bufferDrawBox(uint32_t a0, int32_t a1, int32_t a2, uint32_t a3, uint32_t a4, void * a5, uint32_t a6, void * a7, void * a8, void * a9, void * a10, uint32_t a11, void * a12, uint32_t a13);
static JSValue wrap_bufferDrawBox(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 14) return JS_ThrowTypeError(ctx, "bufferDrawBox: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
int32_t a1; if (JS_ToInt32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
int32_t a2; if (JS_ToInt32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
uint32_t a3; if (JS_ToUint32(ctx, &a3, argv[3]) < 0) return JS_EXCEPTION;
uint32_t a4; if (JS_ToUint32(ctx, &a4, argv[4]) < 0) return JS_EXCEPTION;
void *a5; if (qt_pointer(ctx, argv[5], &a5) < 0) return JS_EXCEPTION;
uint32_t a6; if (JS_ToUint32(ctx, &a6, argv[6]) < 0) return JS_EXCEPTION;
void *a7; if (qt_pointer(ctx, argv[7], &a7) < 0) return JS_EXCEPTION;
void *a8; if (qt_pointer(ctx, argv[8], &a8) < 0) return JS_EXCEPTION;
void *a9; if (qt_pointer(ctx, argv[9], &a9) < 0) return JS_EXCEPTION;
void *a10; if (qt_pointer(ctx, argv[10], &a10) < 0) return JS_EXCEPTION;
uint32_t a11; if (JS_ToUint32(ctx, &a11, argv[11]) < 0) return JS_EXCEPTION;
void *a12; if (qt_pointer(ctx, argv[12], &a12) < 0) return JS_EXCEPTION;
uint32_t a13; if (JS_ToUint32(ctx, &a13, argv[13]) < 0) return JS_EXCEPTION;
bufferDrawBox((uint32_t)a0, (int32_t)a1, (int32_t)a2, (uint32_t)a3, (uint32_t)a4, (void *)a5, (uint32_t)a6, (void *)a7, (void *)a8, (void *)a9, (void *)a10, (uint32_t)a11, (void *)a12, (uint32_t)a13); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void setupTerminal(uint32_t a0, bool a1);
static JSValue wrap_setupTerminal(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "setupTerminal: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
int a1 = JS_ToBool(ctx, argv[1]); if (a1 < 0) return JS_EXCEPTION;
setupTerminal((uint32_t)a0, (bool)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t createTextBuffer(uint8_t a0);
static JSValue wrap_createTextBuffer(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "createTextBuffer: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = createTextBuffer((uint8_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void destroyTextBuffer(uint32_t a0);
static JSValue wrap_destroyTextBuffer(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "destroyTextBuffer: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
destroyTextBuffer((uint32_t)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t textBufferGetLength(uint32_t a0);
static JSValue wrap_textBufferGetLength(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "textBufferGetLength: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = textBufferGetLength((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t textBufferGetByteSize(uint32_t a0);
static JSValue wrap_textBufferGetByteSize(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "textBufferGetByteSize: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = textBufferGetByteSize((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void textBufferSetDefaultFg(uint32_t a0, void * a1);
static JSValue wrap_textBufferSetDefaultFg(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "textBufferSetDefaultFg: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
textBufferSetDefaultFg((uint32_t)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void textBufferSetDefaultBg(uint32_t a0, void * a1);
static JSValue wrap_textBufferSetDefaultBg(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "textBufferSetDefaultBg: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
textBufferSetDefaultBg((uint32_t)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void textBufferSetDefaultAttributes(uint32_t a0, void * a1);
static JSValue wrap_textBufferSetDefaultAttributes(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "textBufferSetDefaultAttributes: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
textBufferSetDefaultAttributes((uint32_t)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void textBufferSetStyledText(uint32_t a0, void * a1, uint32_t a2);
static JSValue wrap_textBufferSetStyledText(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "textBufferSetStyledText: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
textBufferSetStyledText((uint32_t)a0, (void *)a1, (uint32_t)a2); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern bool textBufferSetSyntaxStyle(uint32_t a0, uint32_t a1);
static JSValue wrap_textBufferSetSyntaxStyle(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "textBufferSetSyntaxStyle: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
bool value = textBufferSetSyntaxStyle((uint32_t)a0, (uint32_t)a1); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBool(ctx, value);
}
extern uint32_t createTextBufferView(uint32_t a0);
static JSValue wrap_createTextBufferView(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "createTextBufferView: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t value = createTextBufferView((uint32_t)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void destroyTextBufferView(uint32_t a0);
static JSValue wrap_destroyTextBufferView(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "destroyTextBufferView: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
destroyTextBufferView((uint32_t)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void textBufferViewSetWrapMode(uint32_t a0, uint8_t a1);
static JSValue wrap_textBufferViewSetWrapMode(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "textBufferViewSetWrapMode: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
textBufferViewSetWrapMode((uint32_t)a0, (uint8_t)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void textBufferViewSetFirstLineOffset(uint32_t a0, uint32_t a1);
static JSValue wrap_textBufferViewSetFirstLineOffset(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "textBufferViewSetFirstLineOffset: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
textBufferViewSetFirstLineOffset((uint32_t)a0, (uint32_t)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void textBufferViewSetViewport(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4);
static JSValue wrap_textBufferViewSetViewport(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 5) return JS_ThrowTypeError(ctx, "textBufferViewSetViewport: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
uint32_t a3; if (JS_ToUint32(ctx, &a3, argv[3]) < 0) return JS_EXCEPTION;
uint32_t a4; if (JS_ToUint32(ctx, &a4, argv[4]) < 0) return JS_EXCEPTION;
textBufferViewSetViewport((uint32_t)a0, (uint32_t)a1, (uint32_t)a2, (uint32_t)a3, (uint32_t)a4); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void textBufferViewSetTruncate(uint32_t a0, bool a1);
static JSValue wrap_textBufferViewSetTruncate(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "textBufferViewSetTruncate: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
int a1 = JS_ToBool(ctx, argv[1]); if (a1 < 0) return JS_EXCEPTION;
textBufferViewSetTruncate((uint32_t)a0, (bool)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void bufferDrawTextBufferView(uint32_t a0, uint32_t a1, int32_t a2, int32_t a3);
static JSValue wrap_bufferDrawTextBufferView(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 4) return JS_ThrowTypeError(ctx, "bufferDrawTextBufferView: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
int32_t a2; if (JS_ToInt32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
int32_t a3; if (JS_ToInt32(ctx, &a3, argv[3]) < 0) return JS_EXCEPTION;
bufferDrawTextBufferView((uint32_t)a0, (uint32_t)a1, (int32_t)a2, (int32_t)a3); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t createSyntaxStyle(void);
static JSValue wrap_createSyntaxStyle(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 0) return JS_ThrowTypeError(ctx, "createSyntaxStyle: wrong argument count");
uint32_t value = createSyntaxStyle(); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void destroySyntaxStyle(uint32_t a0);
static JSValue wrap_destroySyntaxStyle(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "destroySyntaxStyle: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
destroySyntaxStyle((uint32_t)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void imageRetainIccCache(void);
static JSValue wrap_imageRetainIccCache(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 0) return JS_ThrowTypeError(ctx, "imageRetainIccCache: wrong argument count");
imageRetainIccCache(); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void imageReleaseIccCache(void);
static JSValue wrap_imageReleaseIccCache(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 0) return JS_ThrowTypeError(ctx, "imageReleaseIccCache: wrong argument count");
imageReleaseIccCache(); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t imageDecode(void * a0, uint32_t a1, void * a2);
static JSValue wrap_imageDecode(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "imageDecode: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
void *a2; if (qt_pointer(ctx, argv[2], &a2) < 0) return JS_EXCEPTION;
uint32_t value = imageDecode((void *)a0, (uint32_t)a1, (void *)a2); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t imageCreateFromRgba(void * a0, uint64_t a1, uint32_t a2, uint32_t a3, uint32_t a4, void * a5);
static JSValue wrap_imageCreateFromRgba(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 6) return JS_ThrowTypeError(ctx, "imageCreateFromRgba: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
int64_t a1; if (JS_ToBigInt64(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
uint32_t a3; if (JS_ToUint32(ctx, &a3, argv[3]) < 0) return JS_EXCEPTION;
uint32_t a4; if (JS_ToUint32(ctx, &a4, argv[4]) < 0) return JS_EXCEPTION;
void *a5; if (qt_pointer(ctx, argv[5], &a5) < 0) return JS_EXCEPTION;
uint32_t value = imageCreateFromRgba((void *)a0, (uint64_t)a1, (uint32_t)a2, (uint32_t)a3, (uint32_t)a4, (void *)a5); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void imageDestroy(uint32_t a0);
static JSValue wrap_imageDestroy(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "imageDestroy: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
imageDestroy((uint32_t)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern uint32_t imageRetain(uint32_t a0, void * a1);
static JSValue wrap_imageRetain(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "imageRetain: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
uint32_t value = imageRetain((uint32_t)a0, (void *)a1); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern uint32_t imageGetInfo(uint32_t a0, void * a1);
static JSValue wrap_imageGetInfo(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "imageGetInfo: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
uint32_t value = imageGetInfo((uint32_t)a0, (void *)a1); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewUint32(ctx, value);
}
extern void getTerminalCapabilities(uint32_t a0, void * a1);
static JSValue wrap_getTerminalCapabilities(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "getTerminalCapabilities: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
getTerminalCapabilities((uint32_t)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void processCapabilityResponse(uint32_t a0, void * a1, uint32_t a2);
static JSValue wrap_processCapabilityResponse(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "processCapabilityResponse: wrong argument count");
uint32_t a0; if (JS_ToUint32(ctx, &a0, argv[0]) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
processCapabilityResponse((uint32_t)a0, (void *)a1, (uint32_t)a2); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern bool encodeUnicode(void * a0, uint32_t a1, void * a2, void * a3, uint8_t a4);
static JSValue wrap_encodeUnicode(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 5) return JS_ThrowTypeError(ctx, "encodeUnicode: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
void *a2; if (qt_pointer(ctx, argv[2], &a2) < 0) return JS_EXCEPTION;
void *a3; if (qt_pointer(ctx, argv[3], &a3) < 0) return JS_EXCEPTION;
uint32_t a4; if (JS_ToUint32(ctx, &a4, argv[4]) < 0) return JS_EXCEPTION;
bool value = encodeUnicode((void *)a0, (uint32_t)a1, (void *)a2, (void *)a3, (uint8_t)a4); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBool(ctx, value);
}
extern void freeUnicode(void * a0, uint32_t a1);
static JSValue wrap_freeUnicode(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "freeUnicode: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
freeUnicode((void *)a0, (uint32_t)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void * yogaNodeCreateForOpenTUI(void);
static JSValue wrap_yogaNodeCreateForOpenTUI(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 0) return JS_ThrowTypeError(ctx, "yogaNodeCreateForOpenTUI: wrong argument count");
void * value = yogaNodeCreateForOpenTUI(); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBigUint64(ctx, (uintptr_t)value);
}
extern void yogaNodeFree(void * a0);
static JSValue wrap_yogaNodeFree(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaNodeFree: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
yogaNodeFree((void *)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeInsertChild(void * a0, void * a1, uint32_t a2);
static JSValue wrap_yogaNodeInsertChild(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "yogaNodeInsertChild: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
yogaNodeInsertChild((void *)a0, (void *)a1, (uint32_t)a2); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeRemoveChild(void * a0, void * a1);
static JSValue wrap_yogaNodeRemoveChild(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "yogaNodeRemoveChild: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
yogaNodeRemoveChild((void *)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeCalculateLayout(void * a0, float a1, float a2, uint32_t a3);
static JSValue wrap_yogaNodeCalculateLayout(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 4) return JS_ThrowTypeError(ctx, "yogaNodeCalculateLayout: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
double a1; if (JS_ToFloat64(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
double a2; if (JS_ToFloat64(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
uint32_t a3; if (JS_ToUint32(ctx, &a3, argv[3]) < 0) return JS_EXCEPTION;
yogaNodeCalculateLayout((void *)a0, (float)a1, (float)a2, (uint32_t)a3); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern bool yogaNodeIsDirty(void * a0);
static JSValue wrap_yogaNodeIsDirty(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaNodeIsDirty: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
bool value = yogaNodeIsDirty((void *)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBool(ctx, value);
}
extern void yogaNodeMarkDirty(void * a0);
static JSValue wrap_yogaNodeMarkDirty(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaNodeMarkDirty: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
yogaNodeMarkDirty((void *)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern bool yogaNodeGetHasNewLayout(void * a0);
static JSValue wrap_yogaNodeGetHasNewLayout(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaNodeGetHasNewLayout: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
bool value = yogaNodeGetHasNewLayout((void *)a0); if (qt_callback_failed(ctx)) return JS_EXCEPTION; return JS_NewBool(ctx, value);
}
extern void yogaNodeSetHasNewLayout(void * a0, bool a1);
static JSValue wrap_yogaNodeSetHasNewLayout(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "yogaNodeSetHasNewLayout: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
int a1 = JS_ToBool(ctx, argv[1]); if (a1 < 0) return JS_EXCEPTION;
yogaNodeSetHasNewLayout((void *)a0, (bool)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeGetComputedLayout(void * a0, void * a1);
static JSValue wrap_yogaNodeGetComputedLayout(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 2) return JS_ThrowTypeError(ctx, "yogaNodeGetComputedLayout: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
void *a1; if (qt_pointer(ctx, argv[1], &a1) < 0) return JS_EXCEPTION;
yogaNodeGetComputedLayout((void *)a0, (void *)a1); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeStyleSetEnum(void * a0, uint32_t a1, uint32_t a2);
static JSValue wrap_yogaNodeStyleSetEnum(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "yogaNodeStyleSetEnum: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
yogaNodeStyleSetEnum((void *)a0, (uint32_t)a1, (uint32_t)a2); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeStyleSetFloat(void * a0, uint32_t a1, float a2);
static JSValue wrap_yogaNodeStyleSetFloat(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "yogaNodeStyleSetFloat: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
double a2; if (JS_ToFloat64(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
yogaNodeStyleSetFloat((void *)a0, (uint32_t)a1, (float)a2); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeStyleSetBorder(void * a0, uint32_t a1, float a2);
static JSValue wrap_yogaNodeStyleSetBorder(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 3) return JS_ThrowTypeError(ctx, "yogaNodeStyleSetBorder: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
double a2; if (JS_ToFloat64(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
yogaNodeStyleSetBorder((void *)a0, (uint32_t)a1, (float)a2); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeStyleSetValue(void * a0, uint32_t a1, uint32_t a2, uint32_t a3, float a4);
static JSValue wrap_yogaNodeStyleSetValue(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 5) return JS_ThrowTypeError(ctx, "yogaNodeStyleSetValue: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
uint32_t a1; if (JS_ToUint32(ctx, &a1, argv[1]) < 0) return JS_EXCEPTION;
uint32_t a2; if (JS_ToUint32(ctx, &a2, argv[2]) < 0) return JS_EXCEPTION;
uint32_t a3; if (JS_ToUint32(ctx, &a3, argv[3]) < 0) return JS_EXCEPTION;
double a4; if (JS_ToFloat64(ctx, &a4, argv[4]) < 0) return JS_EXCEPTION;
yogaNodeStyleSetValue((void *)a0, (uint32_t)a1, (uint32_t)a2, (uint32_t)a3, (float)a4); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeUnsetMeasureFunc(void * a0);
static JSValue wrap_yogaNodeUnsetMeasureFunc(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaNodeUnsetMeasureFunc: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
yogaNodeUnsetMeasureFunc((void *)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaNodeUnsetDirtiedFunc(void * a0);
static JSValue wrap_yogaNodeUnsetDirtiedFunc(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaNodeUnsetDirtiedFunc: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
yogaNodeUnsetDirtiedFunc((void *)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaSetMeasureCallback(void * a0);
static JSValue wrap_yogaSetMeasureCallback(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaSetMeasureCallback: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
yogaSetMeasureCallback((void *)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
extern void yogaSetDirtiedCallback(void * a0);
static JSValue wrap_yogaSetDirtiedCallback(JSContext *ctx, JSValueConst self, int argc, JSValueConst *argv) {
(void)self; if (argc != 1) return JS_ThrowTypeError(ctx, "yogaSetDirtiedCallback: wrong argument count");
void *a0; if (qt_pointer(ctx, argv[0], &a0) < 0) return JS_EXCEPTION;
yogaSetDirtiedCallback((void *)a0); return qt_callback_failed(ctx) ? JS_EXCEPTION : JS_UNDEFINED;
}
int qt_register_symbols(JSContext *ctx, JSValue global) {
JSValue symbols = JS_NewObject(ctx);
if (JS_SetPropertyStr(ctx, symbols, "setLogCallback", JS_NewCFunction(ctx, wrap_setLogCallback, "setLogCallback", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "createEventSink", JS_NewCFunction(ctx, wrap_createEventSink, "createEventSink", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "destroyEventSink", JS_NewCFunction(ctx, wrap_destroyEventSink, "destroyEventSink", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "createNativeRenderable", JS_NewCFunction(ctx, wrap_createNativeRenderable, "createNativeRenderable", 0)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "destroyNativeRenderable", JS_NewCFunction(ctx, wrap_destroyNativeRenderable, "destroyNativeRenderable", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "nativeRenderableAttachYogaNode", JS_NewCFunction(ctx, wrap_nativeRenderableAttachYogaNode, "nativeRenderableAttachYogaNode", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "nativeRenderableSetMeasureTarget", JS_NewCFunction(ctx, wrap_nativeRenderableSetMeasureTarget, "nativeRenderableSetMeasureTarget", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "createRenderer", JS_NewCFunction(ctx, wrap_createRenderer, "createRenderer", 5)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "setTerminalEnvVar", JS_NewCFunction(ctx, wrap_setTerminalEnvVar, "setTerminalEnvVar", 5)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "destroyRenderer", JS_NewCFunction(ctx, wrap_destroyRenderer, "destroyRenderer", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "setUseThread", JS_NewCFunction(ctx, wrap_setUseThread, "setUseThread", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "setBackgroundColor", JS_NewCFunction(ctx, wrap_setBackgroundColor, "setBackgroundColor", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "render", JS_NewCFunction(ctx, wrap_render, "render", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "getNextBuffer", JS_NewCFunction(ctx, wrap_getNextBuffer, "getNextBuffer", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "getCurrentBuffer", JS_NewCFunction(ctx, wrap_getCurrentBuffer, "getCurrentBuffer", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "getBufferWidth", JS_NewCFunction(ctx, wrap_getBufferWidth, "getBufferWidth", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "getBufferHeight", JS_NewCFunction(ctx, wrap_getBufferHeight, "getBufferHeight", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "getBufferWidthMethod", JS_NewCFunction(ctx, wrap_getBufferWidthMethod, "getBufferWidthMethod", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "bufferClear", JS_NewCFunction(ctx, wrap_bufferClear, "bufferClear", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "bufferGetRealCharSize", JS_NewCFunction(ctx, wrap_bufferGetRealCharSize, "bufferGetRealCharSize", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "bufferWriteResolvedChars", JS_NewCFunction(ctx, wrap_bufferWriteResolvedChars, "bufferWriteResolvedChars", 4)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "resizeRenderer", JS_NewCFunction(ctx, wrap_resizeRenderer, "resizeRenderer", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "bufferDrawImage", JS_NewCFunction(ctx, wrap_bufferDrawImage, "bufferDrawImage", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "bufferDrawBox", JS_NewCFunction(ctx, wrap_bufferDrawBox, "bufferDrawBox", 14)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "setupTerminal", JS_NewCFunction(ctx, wrap_setupTerminal, "setupTerminal", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "createTextBuffer", JS_NewCFunction(ctx, wrap_createTextBuffer, "createTextBuffer", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "destroyTextBuffer", JS_NewCFunction(ctx, wrap_destroyTextBuffer, "destroyTextBuffer", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferGetLength", JS_NewCFunction(ctx, wrap_textBufferGetLength, "textBufferGetLength", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferGetByteSize", JS_NewCFunction(ctx, wrap_textBufferGetByteSize, "textBufferGetByteSize", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferSetDefaultFg", JS_NewCFunction(ctx, wrap_textBufferSetDefaultFg, "textBufferSetDefaultFg", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferSetDefaultBg", JS_NewCFunction(ctx, wrap_textBufferSetDefaultBg, "textBufferSetDefaultBg", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferSetDefaultAttributes", JS_NewCFunction(ctx, wrap_textBufferSetDefaultAttributes, "textBufferSetDefaultAttributes", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferSetStyledText", JS_NewCFunction(ctx, wrap_textBufferSetStyledText, "textBufferSetStyledText", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferSetSyntaxStyle", JS_NewCFunction(ctx, wrap_textBufferSetSyntaxStyle, "textBufferSetSyntaxStyle", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "createTextBufferView", JS_NewCFunction(ctx, wrap_createTextBufferView, "createTextBufferView", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "destroyTextBufferView", JS_NewCFunction(ctx, wrap_destroyTextBufferView, "destroyTextBufferView", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferViewSetWrapMode", JS_NewCFunction(ctx, wrap_textBufferViewSetWrapMode, "textBufferViewSetWrapMode", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferViewSetFirstLineOffset", JS_NewCFunction(ctx, wrap_textBufferViewSetFirstLineOffset, "textBufferViewSetFirstLineOffset", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferViewSetViewport", JS_NewCFunction(ctx, wrap_textBufferViewSetViewport, "textBufferViewSetViewport", 5)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "textBufferViewSetTruncate", JS_NewCFunction(ctx, wrap_textBufferViewSetTruncate, "textBufferViewSetTruncate", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "bufferDrawTextBufferView", JS_NewCFunction(ctx, wrap_bufferDrawTextBufferView, "bufferDrawTextBufferView", 4)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "createSyntaxStyle", JS_NewCFunction(ctx, wrap_createSyntaxStyle, "createSyntaxStyle", 0)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "destroySyntaxStyle", JS_NewCFunction(ctx, wrap_destroySyntaxStyle, "destroySyntaxStyle", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "imageRetainIccCache", JS_NewCFunction(ctx, wrap_imageRetainIccCache, "imageRetainIccCache", 0)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "imageReleaseIccCache", JS_NewCFunction(ctx, wrap_imageReleaseIccCache, "imageReleaseIccCache", 0)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "imageDecode", JS_NewCFunction(ctx, wrap_imageDecode, "imageDecode", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "imageCreateFromRgba", JS_NewCFunction(ctx, wrap_imageCreateFromRgba, "imageCreateFromRgba", 6)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "imageDestroy", JS_NewCFunction(ctx, wrap_imageDestroy, "imageDestroy", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "imageRetain", JS_NewCFunction(ctx, wrap_imageRetain, "imageRetain", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "imageGetInfo", JS_NewCFunction(ctx, wrap_imageGetInfo, "imageGetInfo", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "getTerminalCapabilities", JS_NewCFunction(ctx, wrap_getTerminalCapabilities, "getTerminalCapabilities", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "processCapabilityResponse", JS_NewCFunction(ctx, wrap_processCapabilityResponse, "processCapabilityResponse", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "encodeUnicode", JS_NewCFunction(ctx, wrap_encodeUnicode, "encodeUnicode", 5)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "freeUnicode", JS_NewCFunction(ctx, wrap_freeUnicode, "freeUnicode", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeCreateForOpenTUI", JS_NewCFunction(ctx, wrap_yogaNodeCreateForOpenTUI, "yogaNodeCreateForOpenTUI", 0)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeFree", JS_NewCFunction(ctx, wrap_yogaNodeFree, "yogaNodeFree", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeInsertChild", JS_NewCFunction(ctx, wrap_yogaNodeInsertChild, "yogaNodeInsertChild", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeRemoveChild", JS_NewCFunction(ctx, wrap_yogaNodeRemoveChild, "yogaNodeRemoveChild", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeCalculateLayout", JS_NewCFunction(ctx, wrap_yogaNodeCalculateLayout, "yogaNodeCalculateLayout", 4)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeIsDirty", JS_NewCFunction(ctx, wrap_yogaNodeIsDirty, "yogaNodeIsDirty", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeMarkDirty", JS_NewCFunction(ctx, wrap_yogaNodeMarkDirty, "yogaNodeMarkDirty", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeGetHasNewLayout", JS_NewCFunction(ctx, wrap_yogaNodeGetHasNewLayout, "yogaNodeGetHasNewLayout", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeSetHasNewLayout", JS_NewCFunction(ctx, wrap_yogaNodeSetHasNewLayout, "yogaNodeSetHasNewLayout", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeGetComputedLayout", JS_NewCFunction(ctx, wrap_yogaNodeGetComputedLayout, "yogaNodeGetComputedLayout", 2)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeStyleSetEnum", JS_NewCFunction(ctx, wrap_yogaNodeStyleSetEnum, "yogaNodeStyleSetEnum", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeStyleSetFloat", JS_NewCFunction(ctx, wrap_yogaNodeStyleSetFloat, "yogaNodeStyleSetFloat", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeStyleSetBorder", JS_NewCFunction(ctx, wrap_yogaNodeStyleSetBorder, "yogaNodeStyleSetBorder", 3)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeStyleSetValue", JS_NewCFunction(ctx, wrap_yogaNodeStyleSetValue, "yogaNodeStyleSetValue", 5)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeUnsetMeasureFunc", JS_NewCFunction(ctx, wrap_yogaNodeUnsetMeasureFunc, "yogaNodeUnsetMeasureFunc", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaNodeUnsetDirtiedFunc", JS_NewCFunction(ctx, wrap_yogaNodeUnsetDirtiedFunc, "yogaNodeUnsetDirtiedFunc", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaSetMeasureCallback", JS_NewCFunction(ctx, wrap_yogaSetMeasureCallback, "yogaSetMeasureCallback", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
if (JS_SetPropertyStr(ctx, symbols, "yogaSetDirtiedCallback", JS_NewCFunction(ctx, wrap_yogaSetDirtiedCallback, "yogaSetDirtiedCallback", 1)) < 0) { JS_FreeValue(ctx, symbols); return -1; }
return JS_SetPropertyStr(ctx, global, "__native", symbols);
}
